---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn install

script:
  - yarn test

after_success:
  - test $TRAVIS_TAG && node_modules/.bin/ember deploy production --activate
