---
language: node_js
node_js:
  - "lts/*"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  include:
    # runs linting and tests with current locked deps
    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint:hbs
        - npm run lint:js
        - npm run lint:style
        - npm test

before_install:
  - npm config set spin false

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

deploy:
  provider: npm
  email: jon.johnson@ucsf.edu
  api_key: $NPM_TOKEN
  on:
    tags: true
