---
language: node_js
node_js: 'lts/*'
sudo: false
dist: trusty

addons:
  firefox: latest

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - MOZ_HEADLESS=1

before_install:
  - npm config set spin false

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

script:
  - npm run lint:style
  - npm run lint:hbs
  - npm run lint:js
  - npm test
