---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1
  - yarn global add phantomjs-prebuilt
  - phantomjs --version

install: yarn install

before_script: greenkeeper-lockfile-update

script: yarn test

after_script: greenkeeper-lockfile-upload

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && node_modules/.bin/ember deploy staging --activate
  - test $TRAVIS_TAG && node_modules/.bin/ember deploy production --activate
