version: '3.8'
services:
    db:
        image: ilios/mysql-demo:${VERSION_TAG:-v3}
    nginx:
        image: ilios/nginx:${VERSION_TAG:-v3}
        environment:
            - FPM_CONTAINERS=php:9000
        ports:
            - "8000:80"
        volumes:
            - public-web-data:/var/www/ilios/public
    php:
        image: ilios/fpm-dev:${VERSION_TAG:-v3}
        volumes:
            - public-web-data:/var/www/ilios/public
        environment:
            - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=5.6
            - ILIOS_REQUIRE_SECURE_CONNECTION=false
            - ILIOS_ERROR_CAPTURE_ENABLED=false
            - ILIOS_ELASTICSEARCH_HOSTS=elasticsearch
            - ILIOS_FILE_SYSTEM_STORAGE_PATH=/tmp
            - ILIOS_AUTHENTICATION_TYPE=form
    elasticsearch:
        image: ilios/elasticsearch:${VERSION_TAG:-v3}
        environment:
            - discovery.type=single-node
volumes:
    public-web-data:
