name: Auto Merge Labeled Pull Requests

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - reopened
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.8.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_FILTER_AUTHOR: "zorgbort"
          MERGE_FORKS: "false"
          MERGE_DELETE_BRANCH: "true"
          MERGE_RETRY_SLEEP: 90000
