name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '23 1 * * 4' # weekly, on Thursday morning

env:
  CI: true

jobs:
  test:
    name: Lint and Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install dependencies
      run: npm ci
    - name: lint style
      run: npm run lint:style
    - name: lint hbs
      run: npm run lint:hbs
    - name: lint js
      run: npm run lint:js
    - name: test
      run: npm run test:ember
